// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.12.4
// source: alliances.proto

package stfc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllianceEndpoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Details []*AllianceEndpoint_Details `protobuf:"bytes,1,rep,name=details,proto3" json:"details,omitempty"`
	Version string                      `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *AllianceEndpoint) Reset() {
	*x = AllianceEndpoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alliances_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceEndpoint) ProtoMessage() {}

func (x *AllianceEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_alliances_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceEndpoint.ProtoReflect.Descriptor instead.
func (*AllianceEndpoint) Descriptor() ([]byte, []int) {
	return file_alliances_proto_rawDescGZIP(), []int{0}
}

func (x *AllianceEndpoint) GetDetails() []*AllianceEndpoint_Details {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *AllianceEndpoint) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type AlliancesPublicInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AlliancesInfo []*AlliancesPublicInfo_AlliancePublicInfo `protobuf:"bytes,1,rep,name=alliances_info,json=alliancesInfo,proto3" json:"alliances_info,omitempty"`
}

func (x *AlliancesPublicInfo) Reset() {
	*x = AlliancesPublicInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alliances_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlliancesPublicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlliancesPublicInfo) ProtoMessage() {}

func (x *AlliancesPublicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_alliances_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlliancesPublicInfo.ProtoReflect.Descriptor instead.
func (*AlliancesPublicInfo) Descriptor() ([]byte, []int) {
	return file_alliances_proto_rawDescGZIP(), []int{1}
}

func (x *AlliancesPublicInfo) GetAlliancesInfo() []*AlliancesPublicInfo_AlliancePublicInfo {
	if x != nil {
		return x.AlliancesInfo
	}
	return nil
}

type AllianceEndpoint_Details struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    uint32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"` // 71 for protobuf (AlliancesPublicInfo), 42 for JSON?
	Details []byte `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
}

func (x *AllianceEndpoint_Details) Reset() {
	*x = AllianceEndpoint_Details{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alliances_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllianceEndpoint_Details) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllianceEndpoint_Details) ProtoMessage() {}

func (x *AllianceEndpoint_Details) ProtoReflect() protoreflect.Message {
	mi := &file_alliances_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllianceEndpoint_Details.ProtoReflect.Descriptor instead.
func (*AllianceEndpoint_Details) Descriptor() ([]byte, []int) {
	return file_alliances_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AllianceEndpoint_Details) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *AllianceEndpoint_Details) GetDetails() []byte {
	if x != nil {
		return x.Details
	}
	return nil
}

type AlliancesPublicInfo_AlliancePublicInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string                                                      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string                                                      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tag         string                                                      `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	Emblem      uint32                                                      `protobuf:"varint,4,opt,name=emblem,proto3" json:"emblem,omitempty"`
	Unknown1    uint32                                                      `protobuf:"varint,5,opt,name=unknown1,proto3" json:"unknown1,omitempty"`
	Level       uint32                                                      `protobuf:"varint,6,opt,name=level,proto3" json:"level,omitempty"`
	Unknown2    *AlliancesPublicInfo_AlliancePublicInfo_AllianceInfoUnknown `protobuf:"bytes,7,opt,name=unknown2,proto3" json:"unknown2,omitempty"`
	GameworldId uint32                                                      `protobuf:"varint,8,opt,name=gameworld_id,json=gameworldId,proto3" json:"gameworld_id,omitempty"`
}

func (x *AlliancesPublicInfo_AlliancePublicInfo) Reset() {
	*x = AlliancesPublicInfo_AlliancePublicInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alliances_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlliancesPublicInfo_AlliancePublicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlliancesPublicInfo_AlliancePublicInfo) ProtoMessage() {}

func (x *AlliancesPublicInfo_AlliancePublicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_alliances_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlliancesPublicInfo_AlliancePublicInfo.ProtoReflect.Descriptor instead.
func (*AlliancesPublicInfo_AlliancePublicInfo) Descriptor() ([]byte, []int) {
	return file_alliances_proto_rawDescGZIP(), []int{1, 0}
}

func (x *AlliancesPublicInfo_AlliancePublicInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AlliancesPublicInfo_AlliancePublicInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AlliancesPublicInfo_AlliancePublicInfo) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *AlliancesPublicInfo_AlliancePublicInfo) GetEmblem() uint32 {
	if x != nil {
		return x.Emblem
	}
	return 0
}

func (x *AlliancesPublicInfo_AlliancePublicInfo) GetUnknown1() uint32 {
	if x != nil {
		return x.Unknown1
	}
	return 0
}

func (x *AlliancesPublicInfo_AlliancePublicInfo) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *AlliancesPublicInfo_AlliancePublicInfo) GetUnknown2() *AlliancesPublicInfo_AlliancePublicInfo_AllianceInfoUnknown {
	if x != nil {
		return x.Unknown2
	}
	return nil
}

func (x *AlliancesPublicInfo_AlliancePublicInfo) GetGameworldId() uint32 {
	if x != nil {
		return x.GameworldId
	}
	return 0
}

type AlliancesPublicInfo_AlliancePublicInfo_AllianceInfoUnknown struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Unknown1 uint32 `protobuf:"varint,1,opt,name=unknown1,proto3" json:"unknown1,omitempty"`
	Unknown2 uint64 `protobuf:"varint,2,opt,name=unknown2,proto3" json:"unknown2,omitempty"`
}

func (x *AlliancesPublicInfo_AlliancePublicInfo_AllianceInfoUnknown) Reset() {
	*x = AlliancesPublicInfo_AlliancePublicInfo_AllianceInfoUnknown{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alliances_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlliancesPublicInfo_AlliancePublicInfo_AllianceInfoUnknown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlliancesPublicInfo_AlliancePublicInfo_AllianceInfoUnknown) ProtoMessage() {}

func (x *AlliancesPublicInfo_AlliancePublicInfo_AllianceInfoUnknown) ProtoReflect() protoreflect.Message {
	mi := &file_alliances_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlliancesPublicInfo_AlliancePublicInfo_AllianceInfoUnknown.ProtoReflect.Descriptor instead.
func (*AlliancesPublicInfo_AlliancePublicInfo_AllianceInfoUnknown) Descriptor() ([]byte, []int) {
	return file_alliances_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *AlliancesPublicInfo_AlliancePublicInfo_AllianceInfoUnknown) GetUnknown1() uint32 {
	if x != nil {
		return x.Unknown1
	}
	return 0
}

func (x *AlliancesPublicInfo_AlliancePublicInfo_AllianceInfoUnknown) GetUnknown2() uint64 {
	if x != nil {
		return x.Unknown2
	}
	return 0
}

var File_alliances_proto protoreflect.FileDescriptor

var file_alliances_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x61, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x73, 0x74, 0x66, 0x63, 0x22, 0x9f, 0x01, 0x0a, 0x10, 0x41, 0x6c, 0x6c, 0x69,
	0x61, 0x6e, 0x63, 0x65, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x38, 0x0a, 0x07,
	0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x73, 0x74, 0x66, 0x63, 0x2e, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x45, 0x6e, 0x64,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x07, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x1a, 0x37, 0x0a, 0x07, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0xd1, 0x03, 0x0a, 0x13, 0x41, 0x6c,
	0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x53, 0x0a, 0x0e, 0x61, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x73, 0x74, 0x66, 0x63,
	0x2e, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0d, 0x61, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63,
	0x65, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0xe4, 0x02, 0x0a, 0x12, 0x41, 0x6c, 0x6c, 0x69, 0x61,
	0x6e, 0x63, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x74, 0x61, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6d, 0x62, 0x6c, 0x65, 0x6d, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x65, 0x6d, 0x62, 0x6c, 0x65, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x75,
	0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x31, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x75,
	0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x31, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x5c, 0x0a,
	0x08, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x32, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x40, 0x2e, 0x73, 0x74, 0x66, 0x63, 0x2e, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x73,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x41, 0x6c, 0x6c, 0x69, 0x61,
	0x6e, 0x63, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x41, 0x6c,
	0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77,
	0x6e, 0x52, 0x08, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x32, 0x12, 0x21, 0x0a, 0x0c, 0x67,
	0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0b, 0x67, 0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x49, 0x64, 0x1a, 0x4d,
	0x0a, 0x13, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x55, 0x6e,
	0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e,
	0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e,
	0x31, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x32, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x08, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x32, 0x42, 0x1b, 0x5a,
	0x19, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x73, 0x6c, 0x69,
	0x6e, 0x64, 0x73, 0x65, 0x79, 0x2f, 0x73, 0x74, 0x66, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_alliances_proto_rawDescOnce sync.Once
	file_alliances_proto_rawDescData = file_alliances_proto_rawDesc
)

func file_alliances_proto_rawDescGZIP() []byte {
	file_alliances_proto_rawDescOnce.Do(func() {
		file_alliances_proto_rawDescData = protoimpl.X.CompressGZIP(file_alliances_proto_rawDescData)
	})
	return file_alliances_proto_rawDescData
}

var file_alliances_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_alliances_proto_goTypes = []interface{}{
	(*AllianceEndpoint)(nil),                                           // 0: stfc.AllianceEndpoint
	(*AlliancesPublicInfo)(nil),                                        // 1: stfc.AlliancesPublicInfo
	(*AllianceEndpoint_Details)(nil),                                   // 2: stfc.AllianceEndpoint.Details
	(*AlliancesPublicInfo_AlliancePublicInfo)(nil),                     // 3: stfc.AlliancesPublicInfo.AlliancePublicInfo
	(*AlliancesPublicInfo_AlliancePublicInfo_AllianceInfoUnknown)(nil), // 4: stfc.AlliancesPublicInfo.AlliancePublicInfo.AllianceInfoUnknown
}
var file_alliances_proto_depIdxs = []int32{
	2, // 0: stfc.AllianceEndpoint.details:type_name -> stfc.AllianceEndpoint.Details
	3, // 1: stfc.AlliancesPublicInfo.alliances_info:type_name -> stfc.AlliancesPublicInfo.AlliancePublicInfo
	4, // 2: stfc.AlliancesPublicInfo.AlliancePublicInfo.unknown2:type_name -> stfc.AlliancesPublicInfo.AlliancePublicInfo.AllianceInfoUnknown
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_alliances_proto_init() }
func file_alliances_proto_init() {
	if File_alliances_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_alliances_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllianceEndpoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alliances_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlliancesPublicInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alliances_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllianceEndpoint_Details); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alliances_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlliancesPublicInfo_AlliancePublicInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alliances_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlliancesPublicInfo_AlliancePublicInfo_AllianceInfoUnknown); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_alliances_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alliances_proto_goTypes,
		DependencyIndexes: file_alliances_proto_depIdxs,
		MessageInfos:      file_alliances_proto_msgTypes,
	}.Build()
	File_alliances_proto = out.File
	file_alliances_proto_rawDesc = nil
	file_alliances_proto_goTypes = nil
	file_alliances_proto_depIdxs = nil
}
